# Generated by Django 4.2.6 on 2023-11-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketOn', '0003_alter_comprador_correo_alter_comprador_cvv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
