# Generated by Django 4.2.6 on 2023-11-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketOn', '0004_evento_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
