# Generated by Django 4.2.7 on 2023-11-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketOn', '0005_evento_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
