# Generated by Django 4.2.7 on 2023-11-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketOn', '0009_alter_evento_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='slug',
            field=models.SlugField(blank=True, default=0, unique=True),
        ),
    ]
