# Generated by Django 4.1.5 on 2023-11-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TicketOn", "0011_alter_evento_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="codigo",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
