# Generated by Django 4.1.5 on 2023-11-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TicketOn", "0012_alter_ticket_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="fecha_compra",
            field=models.DateField(blank=True, null=True),
        ),
    ]
