# Generated by Django 4.1.5 on 2023-11-18 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("TicketOn", "0013_alter_ticket_fecha_compra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="comprador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="TicketOn.comprador",
            ),
        ),
    ]
