# Generated by Django 4.2.7 on 2023-11-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketOn', '0014_alter_ticket_comprador'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='en_curso',
            field=models.BooleanField(default=True),
        ),
    ]
