# Generated by Django 4.1.5 on 2023-11-19 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("TicketOn", "0015_evento_en_curso"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comprador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TicketOn.comprador",
                    ),
                ),
                (
                    "tickets",
                    models.ManyToManyField(
                        related_name="tickets_en_carrito", to="TicketOn.ticket"
                    ),
                ),
            ],
        ),
    ]
